name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        pip install mlflow

    - name: Run Training
      run: |
        python modelling.py

    # =========================
    # DOCKER STAGE
    # =========================

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.Docker_Username }}
        password: ${{ secrets.Docker_Password }}

    - name: Build Docker Image
      run: |
        mlflow models build-docker -m model -n heart-disease-mlops

    - name: Tag Docker Image
      run: |
        docker tag heart-disease-mlops ${{ secrets.Docker_Username }}/heart-disease-mlops:latest

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.Docker_Username }}/heart-disease-mlops:latest